version: '2'
services:
  lakeside-db:
    image: mysql:5.7.21
    restart: always
    hostname: lakeside-db
    container_name: lakeside-db
    volumes:
      - lakeside-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  lakeside-wp:
    depends_on:
      - lakeside-db
    image: wordpress:4.9.2-php7.0-apache
    restart: always
    hostname: lakeside-wp
    container_name: lakeside-wp
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: lakeside-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    volumes:
      - ./lakeside:/var/www/html/wp-content/themes/hestia-child:rw
      - ./subdivision-shortcodes:/var/www/html/wp-content/plugins/subdivision-shortcodes:rw
volumes:
  lakeside-db:
